language: python

python:
  - 3.6

script:
  - echo "Just build documentation. "

jobs:
  include:
    - stage: documentation
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin devops k8s-ci"